### ISSUE TITLE
Possible to work without floodgate api?

### ISSUE THREAD

**Issue by EcoSMP** [tdherring/geyser-interaction-fix#1]
If we use the floodgate api on our back-end servers and not only the proxy, this requires send-floodgate-data to be set to true. This blocks Bedrock players from being able to join some of the back-end servers. 

For this reason, we are wondering if this plugin would still work to block Geyser/Bedrock players from being able to open doors/trapdoors even if we don't have floodgate on the back-end spigot servers?

Thanks!

**Comment by tdherring** [comment]
Hey, and thanks for your question!

Unfortunately this isn't possible with the plugin in its current state. It relies on the Floodgate API to check whether a player is on Bedrock.

Prior to using the API, I did a check for the Floodgate prefix (say * or .), however this meant that linked players would be excluded from the check, which isn't ideal. See this commit for that change: https://github.com/tdherring/geyser-interaction-fix/commit/2cb09f0b5b2210059b3c38738ce5fd2ef121086a

**Comment by EcoSMP** [comment]
Thanks for the response! We are attempting to use the plugin while having Floodgate on the back-end spigot server just without enabling send-floodgate-data on proxy. Im not sure if that will work or not

**Comment by EcoSMP** [comment]
This does not work without sending floogate data from the proxy. Any chance we could get a copy of the old version that did not yet use the Floodgate API? I understand it is not 100% secure but it would be better than what we currently have where all Bedrock players can open any locked door/trapdoor. Thanks for your consideration!

**Comment by tdherring** [comment]
Apologies for not coming back to you, been super busy!

Of course, if you're able to give me a couple of days I'll get the jar for the old version to you by Sunday.

**Comment by EcoSMP** [comment]
We greatly appreciate that!

**Comment by tdherring** [comment]
Hey again,

I've updated the releases page to include the old version. You can find it here: https://github.com/tdherring/geyser-interaction-fix/releases/tag/v1.1.0

Please let me know if I can be of anymore help!
